app:
    baseUrl: https://springsecuritybackend-production-1792.up.railway.app
    railway:
        jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        jwtExpirationMs: 8640000
        #shop token
spring:
    datasource:
        url: jdbc:postgresql://roundhouse.proxy.rlwy.net:23980/railway
        #          postgresql://postgres:ClCmYoFmscBKWTOSxGlQXpVJUuhfePeQ@roundhouse.proxy.rlwy.net:23980/railway
        #url: jdbc:postgresql://postgres:ClCmYoFmscBKWTOSxGlQXpVJUuhfePeQ@roundhouse.proxy.rlwy.net:23980/railway
        username: postgres
        password: ClCmYoFmscBKWTOSxGlQXpVJUuhfePeQ
        #host: roundhouse.proxy.rlwy.net
        #port: 23980
        #database: railway
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
            format-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: smtp.gmail.com
        port: 587
        username: "Marta.software.noreply@gmail.com"
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        password: "jruhiipfmgkagjcx"
    #data:
    #    mongodb:
    #        url: mongodb://mongo:lOdFnL426Z2wJUgv4C8A@containers-us-west-42.railway.app:7675
    #        authentication-database: admin
    #        username: mongo
    #        password: lOdFnL426Z2wJUgv4C8A
    #        port: 7675
    #        host: containers-us-west-42.railway.app
    #mvc:
    #    pathmatch:
    #        matching-strategy: ant_path_matcher ab
server:
    port: ${PORT:3000}